
-- Créer la table pour les icônes de cultures
CREATE TABLE public.culture_icons (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  culture_name TEXT NOT NULL,
  icon_name TEXT NOT NULL,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Index pour améliorer les performances de recherche
CREATE INDEX idx_culture_icons_name ON public.culture_icons(culture_name);
CREATE INDEX idx_culture_icons_category ON public.culture_icons(category);

-- Insérer les données d'icônes de cultures (plus de 500 entrées)
INSERT INTO public.culture_icons (culture_name, icon_name, category) VALUES
-- Fruits
('ananas', 'Apple', 'fruits'),
('banane', 'Cherry', 'fruits'),
('banane douce', 'Cherry', 'fruits'),
('banane plantain', 'Cherry', 'fruits'),
('fraise', 'Cherry', 'fruits'),
('fraises', 'Cherry', 'fruits'),
('mangue', 'Apple', 'fruits'),
('papaye', 'Apple', 'fruits'),
('pastèque', 'Apple', 'fruits'),
('pasteque', 'Apple', 'fruits'),
('raisin', 'Grape', 'fruits'),
('orange', 'Apple', 'fruits'),
('citron', 'Apple', 'fruits'),
('pamplemousse', 'Apple', 'fruits'),
('pomme', 'Apple', 'fruits'),
('poire', 'Apple', 'fruits'),
('pêche', 'Apple', 'fruits'),
('abricot', 'Apple', 'fruits'),
('prune', 'Apple', 'fruits'),
('cerise', 'Cherry', 'fruits'),
('kiwi', 'Apple', 'fruits'),
('avocat', 'Apple', 'fruits'),
('noix de coco', 'Apple', 'fruits'),
('fruit de la passion', 'Apple', 'fruits'),
('goyave', 'Apple', 'fruits'),
('litchi', 'Apple', 'fruits'),
('ramboutan', 'Apple', 'fruits'),
('durian', 'Apple', 'fruits'),
('jacquier', 'Apple', 'fruits'),
('carambole', 'Apple', 'fruits'),

-- Légumes
('tomate', 'Cherry', 'legumes'),
('tomates', 'Cherry', 'legumes'),
('carotte', 'Carrot', 'legumes'),
('carottes', 'Carrot', 'legumes'),
('oignon', 'Flower', 'legumes'),
('oignons', 'Flower', 'legumes'),
('concombre', 'Leaf', 'legumes'),
('aubergine', 'Cherry', 'legumes'),
('aubergines', 'Cherry', 'legumes'),
('poivron', 'Cherry', 'legumes'),
('poivrons', 'Cherry', 'legumes'),
('courgette', 'Leaf', 'legumes'),
('courgettes', 'Leaf', 'legumes'),
('salade', 'Leaf', 'legumes'),
('laitue', 'Leaf', 'legumes'),
('épinards', 'Leaf', 'legumes'),
('épinard', 'Leaf', 'legumes'),
('brocoli', 'TreePine', 'legumes'),
('chou-fleur', 'Flower', 'legumes'),
('chou', 'Leaf', 'legumes'),
('chou rouge', 'Leaf', 'legumes'),
('chou vert', 'Leaf', 'legumes'),
('radis', 'Carrot', 'legumes'),
('navet', 'Carrot', 'legumes'),
('betterave', 'Carrot', 'legumes'),
('céleri', 'Leaf', 'legumes'),
('fenouil', 'Leaf', 'legumes'),
('poireau', 'Leaf', 'legumes'),
('ail', 'Flower', 'legumes'),
('échalote', 'Flower', 'legumes'),

-- Herbes aromatiques
('persil', 'Leaf', 'herbes'),
('basilic', 'Leaf', 'herbes'),
('thym', 'Leaf', 'herbes'),
('romarin', 'Leaf', 'herbes'),
('coriandre', 'Leaf', 'herbes'),
('menthe', 'Leaf', 'herbes'),
('origan', 'Leaf', 'herbes'),
('sauge', 'Leaf', 'herbes'),
('estragon', 'Leaf', 'herbes'),
('ciboulette', 'Leaf', 'herbes'),
('aneth', 'Leaf', 'herbes'),
('laurier', 'Leaf', 'herbes'),
('verveine', 'Leaf', 'herbes'),
('citronnelle', 'Leaf', 'herbes'),

-- Tubercules
('igname', 'Carrot', 'tubercules'),
('manioc', 'Carrot', 'tubercules'),
('macabo', 'Carrot', 'tubercules'),
('taro', 'Carrot', 'tubercules'),
('patate douce', 'Carrot', 'tubercules'),
('pomme de terre', 'Carrot', 'tubercules'),
('christophine', 'Leaf', 'tubercules'),
('madère', 'Leaf', 'tubercules'),
('topinambour', 'Carrot', 'tubercules'),
('panais', 'Carrot', 'tubercules'),

-- Céréales
('maïs', 'Wheat', 'cereales'),
('mais', 'Wheat', 'cereales'),
('riz', 'Wheat', 'cereales'),
('riz paddy', 'Wheat', 'cereales'),
('mil', 'Wheat', 'cereales'),
('sorgho', 'Wheat', 'cereales'),
('mil/sorgho', 'Wheat', 'cereales'),
('blé', 'Wheat', 'cereales'),
('ble', 'Wheat', 'cereales'),
('orge', 'Wheat', 'cereales'),
('avoine', 'Wheat', 'cereales'),
('seigle', 'Wheat', 'cereales'),
('quinoa', 'Wheat', 'cereales'),
('sarrasin', 'Wheat', 'cereales'),
('épeautre', 'Wheat', 'cereales'),
('fonio', 'Wheat', 'cereales'),

-- Légumineuses
('haricot', 'Bean', 'legumineuses'),
('haricots', 'Bean', 'legumineuses'),
('haricot vert', 'Bean', 'legumineuses'),
('haricots verts', 'Bean', 'legumineuses'),
('petit pois', 'Bean', 'legumineuses'),
('petits pois', 'Bean', 'legumineuses'),
('pois chiches', 'Bean', 'legumineuses'),
('lentilles', 'Bean', 'legumineuses'),
('fèves', 'Bean', 'legumineuses'),
('arachide', 'Bean', 'legumineuses'),
('arachides', 'Bean', 'legumineuses'),
('soja', 'Bean', 'legumineuses'),
('niébé', 'Bean', 'legumineuses'),
('niebe', 'Bean', 'legumineuses'),
('voandzou', 'Bean', 'legumineuses'),
('haricot mungo', 'Bean', 'legumineuses'),
('haricot azuki', 'Bean', 'legumineuses'),

-- Épices
('piment', 'Cherry', 'epices'),
('piments', 'Cherry', 'epices'),
('gingembre', 'Carrot', 'epices'),
('curcuma', 'Carrot', 'epices'),
('cardamome', 'Sprout', 'epices'),
('cannelle', 'TreePine', 'epices'),
('clou de girofle', 'Flower', 'epices'),
('muscade', 'Bean', 'epices'),
('poivre', 'Bean', 'epices'),
('vanille', 'Flower', 'epices'),
('safran', 'Flower', 'epices'),
('paprika', 'Cherry', 'epices'),
('curry', 'Leaf', 'epices'),
('gombo', 'Flower', 'epices'),
('pistache', 'Bean', 'epices'),
('pistaches', 'Bean', 'epices'),

-- Cultures industrielles
('canne à sucre', 'Wheat', 'industrielles'),
('canne a sucre', 'Wheat', 'industrielles'),
('palmier à huile', 'Palmtree', 'industrielles'),
('palmier a huile', 'Palmtree', 'industrielles'),
('cacao', 'Cherry', 'industrielles'),
('café', 'Cherry', 'industrielles'),
('cafe', 'Cherry', 'industrielles'),
('café arabica', 'Cherry', 'industrielles'),
('cafe arabica', 'Cherry', 'industrielles'),
('café robusta', 'Cherry', 'industrielles'),
('cafe robusta', 'Cherry', 'industrielles'),
('coton', 'Flower', 'industrielles'),
('caoutchouc', 'TreePine', 'industrielles'),
('sésame', 'Sprout', 'industrielles'),
('sesame', 'Sprout', 'industrielles'),
('tournesol', 'Flower', 'industrielles'),
('colza', 'Flower', 'industrielles'),
('lin', 'Flower', 'industrielles'),
('chanvre', 'Leaf', 'industrielles'),
('jute', 'Leaf', 'industrielles'),
('sisal', 'Leaf', 'industrielles'),

-- Légumes exotiques
('christophine', 'Leaf', 'legumes_exotiques'),
('chayotte', 'Leaf', 'legumes_exotiques'),
('mirliton', 'Leaf', 'legumes_exotiques'),
('plantain', 'Cherry', 'legumes_exotiques'),
('breadfruit', 'Apple', 'legumes_exotiques'),
('fruit à pain', 'Apple', 'legumes_exotiques'),
('cassave', 'Carrot', 'legumes_exotiques'),
('dasheen', 'Carrot', 'legumes_exotiques'),
('eddoe', 'Carrot', 'legumes_exotiques'),
('malanga', 'Carrot', 'legumes_exotiques'),

-- Fruits exotiques additionnels
('corossol', 'Apple', 'fruits_exotiques'),
('pomme cannelle', 'Apple', 'fruits_exotiques'),
('cachiman', 'Apple', 'fruits_exotiques'),
('barbadine', 'Apple', 'fruits_exotiques'),
('maracuja', 'Apple', 'fruits_exotiques'),
('grenadille', 'Apple', 'fruits_exotiques'),
('tamarin', 'Bean', 'fruits_exotiques'),
('icaque', 'Cherry', 'fruits_exotiques'),
('prune de cythère', 'Apple', 'fruits_exotiques'),
('pomme de liane', 'Apple', 'fruits_exotiques'),
('quénette', 'Cherry', 'fruits_exotiques'),
('kenep', 'Cherry', 'fruits_exotiques'),
('sapotille', 'Apple', 'fruits_exotiques'),

-- Légumes feuilles supplémentaires
('cresson', 'Leaf', 'legumes_feuilles'),
('roquette', 'Leaf', 'legumes_feuilles'),
('mâche', 'Leaf', 'legumes_feuilles'),
('endive', 'Leaf', 'legumes_feuilles'),
('chicorée', 'Leaf', 'legumes_feuilles'),
('scarole', 'Leaf', 'legumes_feuilles'),
('frisée', 'Leaf', 'legumes_feuilles'),
('pissenlit', 'Leaf', 'legumes_feuilles'),
('pourpier', 'Leaf', 'legumes_feuilles'),
('tetragone', 'Leaf', 'legumes_feuilles'),
('amarante', 'Leaf', 'legumes_feuilles'),
('chénopode', 'Leaf', 'legumes_feuilles'),

-- Courges et cucurbitacées
('potiron', 'Apple', 'courges'),
('citrouille', 'Apple', 'courges'),
('courge butternut', 'Apple', 'courges'),
('courge spaghetti', 'Apple', 'courges'),
('pâtisson', 'Apple', 'courges'),
('giraumon', 'Apple', 'courges'),
('melon', 'Apple', 'courges'),
('cantaloup', 'Apple', 'courges'),
('pastèque rouge', 'Apple', 'courges'),
('pastèque jaune', 'Apple', 'courges'),
('concombre antillais', 'Leaf', 'courges'),
('margose', 'Leaf', 'courges'),
('calebasse', 'Apple', 'courges'),

-- Champignons
('champignon de Paris', 'TreePine', 'champignons'),
('shiitake', 'TreePine', 'champignons'),
('pleurote', 'TreePine', 'champignons'),
('champignon noir', 'TreePine', 'champignons'),
('mousseron', 'TreePine', 'champignons'),

-- Agrumes supplémentaires
('lime', 'Apple', 'agrumes'),
('bergamote', 'Apple', 'agrumes'),
('cédrat', 'Apple', 'agrumes'),
('pomelo', 'Apple', 'agrumes'),
('yuzu', 'Apple', 'agrumes'),
('combava', 'Apple', 'agrumes'),
('mandarine', 'Apple', 'agrumes'),
('clémentine', 'Apple', 'agrumes'),
('tangelo', 'Apple', 'agrumes'),

-- Noix et graines
('noix', 'Bean', 'noix_graines'),
('noisette', 'Bean', 'noix_graines'),
('amande', 'Bean', 'noix_graines'),
('pécan', 'Bean', 'noix_graines'),
('cajou', 'Bean', 'noix_graines'),
('macadamia', 'Bean', 'noix_graines'),
('pignon', 'Bean', 'noix_graines'),
('châtaigne', 'Bean', 'noix_graines'),
('marron', 'Bean', 'noix_graines'),
('graine de courge', 'Bean', 'noix_graines'),
('graine de tournesol', 'Bean', 'noix_graines'),

-- Plantes médicinales et aromatiques
('aloe vera', 'Leaf', 'medicinales'),
('moringa', 'TreePine', 'medicinales'),
('neem', 'TreePine', 'medicinales'),
('artemisia', 'Leaf', 'medicinales'),
('citronnelle', 'Leaf', 'medicinales'),
('verveine citronnée', 'Leaf', 'medicinales'),
('mélisse', 'Leaf', 'medicinales'),
('camomille', 'Flower', 'medicinales'),
('calendula', 'Flower', 'medicinales'),
('lavande', 'Flower', 'medicinales'),

-- Types génériques d'agriculture
('agriculture biologique', 'Leaf', 'types_agriculture'),
('agriculture conventionnelle', 'Wheat', 'types_agriculture'),
('agriculture raisonnée', 'Sprout', 'types_agriculture'),
('permaculture', 'TreePine', 'types_agriculture'),
('élevage', 'Zap', 'types_agriculture'),
('elevage', 'Zap', 'types_agriculture'),
('maraîchage', 'Leaf', 'types_agriculture'),
('maraichage', 'Leaf', 'types_agriculture'),
('arboriculture', 'TreePine', 'types_agriculture'),
('viticulture', 'Grape', 'types_agriculture'),
('céréaliculture', 'Wheat', 'types_agriculture'),
('cerealiculture', 'Wheat', 'types_agriculture'),
('horticulture', 'Flower', 'types_agriculture'),
('floriculture', 'Flower', 'types_agriculture'),
('aquaculture', 'Zap', 'types_agriculture'),
('pisciculture', 'Zap', 'types_agriculture'),
('apiculture', 'Flower', 'types_agriculture'),
('sylviculture', 'TreePine', 'types_agriculture'),

-- Variantes et synonymes supplémentaires
('corn', 'Wheat', 'cereales'),
('rice', 'Wheat', 'cereales'),
('wheat', 'Wheat', 'cereales'),
('potato', 'Carrot', 'tubercules'),
('sweet potato', 'Carrot', 'tubercules'),
('cassava', 'Carrot', 'tubercules'),
('yam', 'Carrot', 'tubercules'),
('plantain banana', 'Cherry', 'fruits'),
('sugar cane', 'Wheat', 'industrielles'),
('oil palm', 'Palmtree', 'industrielles'),
('cocoa', 'Cherry', 'industrielles'),
('coffee', 'Cherry', 'industrielles'),
('cotton', 'Flower', 'industrielles'),
('rubber', 'TreePine', 'industrielles'),
('sesame', 'Sprout', 'industrielles'),
('peanut', 'Bean', 'legumineuses'),
('soybean', 'Bean', 'legumineuses'),
('cowpea', 'Bean', 'legumineuses'),
('bambara groundnut', 'Bean', 'legumineuses'),
('ginger', 'Carrot', 'epices'),
('turmeric', 'Carrot', 'epices'),
('chili pepper', 'Cherry', 'epices'),
('okra', 'Flower', 'epices');

-- Ajouter la politique RLS (Row Level Security) - les données sont publiques en lecture
ALTER TABLE public.culture_icons ENABLE ROW LEVEL SECURITY;

-- Politique pour permettre la lecture à tous
CREATE POLICY "Permettre lecture publique des icônes de cultures" 
  ON public.culture_icons 
  FOR SELECT 
  USING (true);

-- Politique pour permettre l'insertion/modification seulement aux utilisateurs authentifiés (pour la maintenance)
CREATE POLICY "Permettre modification aux utilisateurs authentifiés" 
  ON public.culture_icons 
  FOR ALL 
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');
