// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoobbkzxekttshtsrcht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2Jia3p4ZWt0dHNodHNyY2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjM0ODIsImV4cCI6MjA2NTQzOTQ4Mn0.10cDm_bDyDzUI0AsNQzSQxCZvvVBUggtih_yraW1iFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);